@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.spawner;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;