@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.concurrent;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;