@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.status;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;