@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.datasync;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;