@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.util;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;