@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mojang.blaze3d.vertex;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;