@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mojang.realmsclient.client;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;