@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.impl;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;