@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.state.properties;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;