@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.dedicated;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;