@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.login;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;