@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.settings;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;