@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.inventory.container;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;