@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.lighting;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;