@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.pathfinding;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;