@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.loot.conditions;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;