@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.registry;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;