@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.integrated;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;