@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.datafix.versions;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;