@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block.pattern;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;