@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.palette;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;