@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.enchantment;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;