@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.entity.player;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;