@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.multiplayer;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;