@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.tutorial;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;