@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.shader;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;