@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.item.crafting;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;