@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.login.server;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;