@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.audio;

import me.sertyo.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;